### ISSUE TITLE
render :stream is required for Rails 5

### ISSUE THREAD

**Issue by patrickemuller** [jarthod/render-later#1]
Hey @jarthod I just saw your comment on issue [#11476](https://github.com/rails/rails/issues/11476) from Rails Project and it would be great if you could point some info about this problem on the README of your Gem.
I can create a PR adding this info too, just let me know what you prefer.
Your idea for this Gem is great I think it should be kept update =)

**Comment by jarthod** [comment]
Hey, thanks for your interest ;)
It's already there in the [Flash message & CSRF token](https://github.com/jarthod/render-later#flash-message--csrf-token) section, are you thinking about something else?

**Comment by jarthod** [comment]
Ah I see from the title you're talking about `render :stream` too, indeed it seems I forgot to put that in the usage section, I'll add it !

**Comment by jarthod** [comment]
Ok I added a note about this in the [usage section](https://github.com/jarthod/render-later#usage).
Let me know if you think we need something else ;)

**Comment by patrickemuller** [comment]
Great @jarthod !
Thanks for your time doing this. I think this way it's clear to understand that this is required on Rails 5+ :)
Good Job !

**Comment by jarthod** [comment]
You're welcome ;)
`render :stream` is actually required for any Rails version, not only 5+, otherwise rails doesn't stream so it works but without any performance gain.
