### ISSUE TITLE
Not working for table rows

### ISSUE THREAD

**Issue by octavpo** [jarthod/render-later#2]
This gem looks like potentially very useful to my project, where I have to display long lists of items on a page. Unlike in your example, none of the info in a line is particularly slow, as they are just fields in a collection, it's just a few pretty large collections (one per page on different pages). So I'm trying to apply the render_later helper to each row in a table. So for instance in a _problems.html.slim partial that's part of the index.html.slim template for the problems_controller I have lines like:

```slim
...
div
  table#problems_table
    thead = render 'header'
    tbody = render @problems
...
```

while in the _problem.html.slim partial I have something like:

```slim
= render_later "problem_#{problem.id}" do
  tr
    td.name = problem.name
    td.file = problem.file
...
```

And I also added a

```slim
= render_now
```

to the layout's body and I have a 

```rb
render stream: true
```

 in the index action.

It doesn't quite work. I do see the layout and the table header showing quickly, and then the table content starts showing line by line, and I do get all of it. However the table content consists only of concatenated cell content, stripped of tr and td elements, and it's added on top of the table, instead of inside it. 

The page works fine without the streaming, or even just with the render stream: true in the action, but it shows the whole table content in one step, when all of it is ready, which is of course what I hope to avoid by using your gem.

What am I doing wrong? Do you have a working example where the table you show in your documentation works like this, with entire lines being streamed one by one, rather than just the content of one column, so I can see how to do it? Or is this an issue with the gem?

Thanks

**Comment by jarthod** [comment]
Good point, there was 2 issues preventing this:
1. The placeholder is a `span` element by default, which is not allowed inside a table, I've added an option to customize it, we'll need to use `tr` in your case, ex: `render_later "problem_#{problem.id}", tag: :tr do`
2. The javascript was using a temporary `div` element to parse the deferred content before inserting it into the DOM, and this would not work with a `tr` element (not allowed inside a div) so I fixed this by creating a temporary element of the same time as the parent node (`table` in your case)

These fixes have been released as `1.1.0`, please give them a try and let me know if it works for you.

But your case doesn't look like a legit use of this library to me, the point of `render-later` is to defer some parts so you can see other parts quickly, if you defer the whole line, you're pretty much doing simple streaming and just rendering your page streamed would be the simplest and faster way IMO. If you can't get your page to render streamed without `render-later` you may want to work on that instead ;)

**Comment by octavpo** [comment]
Yes it works great now, thanks.

If by rendering the page streamed you mean just using render stream: true in the action, I tried that and it doesn't work. That is I can see the layout coming before the template, but then the template still shows all in one piece when all rows are available. No idea what to do about it.

**Comment by jarthod** [comment]
Ok great!

Well I guess your main loop is not streamable then, are you using `.map` or other collecting methods? Are you using some helpers to renders the whole thing? If you have a simple each loop in slim or erb it should be streamable, if it's in a helper it won't (unless you're using the `concat` method to append content and not the return value)

**Comment by octavpo** [comment]
The collection is generated by a single more complex lazy relation. Today I kept removing stuff from both the layout and the template, to the point where the layout is just:

```slim
doctype html
html lang = 'en'
  head
    title Mathtutor
    meta charset = 'utf-8'
    = stylesheet_link_tag 'application', media: 'all'
  body
    h1 Mathtutor
    #page
      main#main = yield
```

and the template is:

```slim
section#content.list_view
  h1 Problems
  .content
    table#problems_table
      thead
        tr
          th.filter Label
          th.problem_name Name
          th.problemset_name Problem Set
          th.package_name Package
          th.problem_file Problem File
          th.problem_file Interface
          th.actions3 Actions
      tbody = render @problems
```
and still nothing, it still comes all in one piece. I even replaced the last line with:

```slim
      tbody
        - @problems.each do |problem|
          = render problem
```

and still nothing. I even removed the stylesheet, still nothing. I'm out of ideas. Works fine with your gem though so I guess I'll keep using it. Thanks.

**Comment by jarthod** [comment]
Ok weird, with the render collection I'm not sure but with the `each` (your last example) I would expect this to work, there must be something else going in the way ☹
Streaming is an old and awesome feature to very simply improve web performance for everyone, It's sad Rails doesn't care more about it.
